import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "./components/Sidebar";
import "./globals.css";
import TopLoader from "./components/TopLoader";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mail Master",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-950 text-gray-100 flex">
        <Suspense fallback={null}>
          <TopLoader />
        </Suspense>
        <Sidebar />
        {/* The ml-64 pushes the content over to make room for the fixed sidebar */}
        <main className="ml-64 flex-1">
          {children}
        </main>
      </body>
    </html>
  );
}
